FROM debian:wheezy
MAINTAINER Alexey Nurmukhametov <nurmukhametov.alex@gmail.com>

RUN apt-get update
RUN apt-get install -y python3 libzmq1 python3-zmq python3-requests

RUN apt-get install -y clamav
RUN freshclam
COPY plaguescanner.conf /opt/
COPY clam-agent.py /opt/

CMD PYTHONUNBUFFERED=0 /opt/clam-agent.py
